networks:
  dev:

services:
  nginx:
    networks:
      - dev
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
      - job_finder_service

  backend:
    build:
      context: ./find_job_service
    depends_on:
      - job_finder_service
    networks:
      - dev

  frontend:
    ports:
      - "3000:3000"
    build:
      context: ./job-finder-frontend
    depends_on:
      - job_finder_service
    environment:
      - PORT=3000
    networks:
      - dev


  job_finder_service:
    networks:
      - dev
    container_name: job_finder
    image: postgres:17.5
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/data/postgres
    restart: unless-stopped